In [1]:
import numpy as np

# Аттрибуты:

In [2]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [3]:
type(A)

numpy.ndarray

In [4]:
A.shape

(3,)

In [5]:
A.size

3

In [6]:
A.dtype

dtype('int64')

In [7]:
A.ndim

1

In [8]:
A.itemsize

8

In [9]:
A.data

# Создание ndarray:

In [10]:
A = np.ones((3, 3,))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
A.ndim, A.size, A.shape, A.itemsize

(2, 9, (3, 3), 8)

функции `empty`, `zeros`,  `ones`, `full`, `random`, `arange` позволяют создать массивы, заполненные заранее определенными элементами:

In [12]:
??np.empty

In [13]:
A = np.arange(0, 10, 2, dtype=np.float16)
A

array([0., 2., 4., 6., 8.], dtype=float16)

In [14]:
A.itemsize

2

In [15]:
B = A > 3
B

array([False, False,  True,  True,  True])

In [16]:
B.dtype

dtype('bool')

Задания: 
* создать массив из списка разных типов (строк, списков, кортежей)
* посмотреть на все аттрибуты
* создать еще что-нибудь

# Индексация
numpy поддерживает такую же индексацию как у листов

In [17]:
A = np.random.random((5))
A

array([0.33163234, 0.23555143, 0.00625945, 0.88605592, 0.88167664])

In [18]:
A[-1]

0.881676637164945

In [19]:
A[1:3]

array([0.23555143, 0.00625945])

In [20]:
A[::2]

array([0.33163234, 0.00625945, 0.88167664])

индексация ndarray умеет много вещей, с которыми list не справляется:

In [21]:
# индексация списком
A[[1, -1]]

array([0.23555143, 0.88167664])

In [22]:
# индексация булевым списком (шейп должен совпадать с шейпом самого массива)
A[[True, True, False, False, False]]

array([0.33163234, 0.23555143])

In [23]:
A[A < 0.5]

array([0.33163234, 0.23555143, 0.00625945])

In [24]:
# inplace!
A[A < 0.5] = 0
A

array([0.        , 0.        , 0.        , 0.88605592, 0.88167664])

Задания:
* заменить все нечетные числа в массиве на None (для создания можно использовать np.random.randint)
* напечатать массив в обратном порядке

## Индексация n-мерных массивов:

In [25]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
A[:, 0]

array([1., 0., 0., 0., 0.])

In [27]:
A[:, [0, 1, 2, 3, 4]]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# поменять столбцы местами:
A[:, [4, 1, 2, 3, 0]]

array([[0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.]])

In [29]:
A[..., -1]

array([0., 0., 0., 0., 1.])

In [30]:
A == 1

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [31]:
A[A == 1]

array([1., 1., 1., 1., 1.])

Задания:
* создать массив из случайных значений из промежутка 0, 10, и заменить все значения из промежутка (3, 7) на None
* one-hot encoding: для заданного массива integer значений написать функцию, которая преобразует каждое из них в one-hot вектор (число i преобразуется в вектор, на i месте которого стоит 1, а на всех остальных нолики)

In [ ]:
lst = np.random.randint(0, high=10, size=(10))
def one_hot(lst):
    ### YOUR CODE IN HERE

In [ ]:
_ = one_hot(lst)

# Magic time!
* %time позволяет засечь время выполнения строки
* %%time позволяет засечь время выполнения одной ячейки
* %%timeit многократно повторяет одну ячейку и выдает статистику по времени запуска
* %%prun -- профилировщик кода

# Re-shape
функции/методы `ravel` и `reshape` позволяют изменить форму хранения данных, не трогая при этом сами данные


In [32]:
A = np.arange(0, 24)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
reshaped = A.reshape(4, 3, 2)
reshaped

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [34]:
A.reshape(-1, 3, 2)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
reshaped.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
reshaped.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Задания:
* создать массив данных, где первая строчка -- [0, 100, 200], а каждая следующая получена прибавлением к предыдущей строчке 300, т.е. следующая строка [300, 400, 500], дальше [600, 700, 800], и т.д. Всего N строк.

# Методы
у ndarray много методов: min, max, mean, argsort...
многие из них принимают аргумент axis: по какой из осей применить преобразование

In [37]:
A = np.random.randint(0, 10, (5, 8))
A

array([[6, 6, 5, 6, 3, 5, 9, 9],
       [2, 6, 3, 4, 1, 6, 9, 3],
       [2, 4, 4, 5, 3, 3, 0, 3],
       [0, 1, 1, 8, 4, 4, 0, 1],
       [1, 3, 9, 2, 0, 3, 0, 3]])

In [38]:
A.sum()

147

In [39]:
A.sum(axis=0)

array([11, 20, 22, 25, 11, 21, 18, 19])

In [40]:
A.sum(axis=1)

array([49, 34, 24, 19, 21])

In [41]:
A.argsort()

array([[4, 2, 5, 0, 1, 3, 6, 7],
       [4, 0, 2, 7, 3, 1, 5, 6],
       [6, 0, 4, 5, 7, 1, 2, 3],
       [0, 6, 1, 2, 7, 4, 5, 3],
       [4, 6, 0, 3, 1, 5, 7, 2]])

In [42]:
A.argsort()

array([[4, 2, 5, 0, 1, 3, 6, 7],
       [4, 0, 2, 7, 3, 1, 5, 6],
       [6, 0, 4, 5, 7, 1, 2, 3],
       [0, 6, 1, 2, 7, 4, 5, 3],
       [4, 6, 0, 3, 1, 5, 7, 2]])

Задания:
* отсортировать 2д массив по значениям в третьей колонке
* вывести max/min значения по строкам; заменить все элементы, равные минимуму, на -np.inf

# Операции
операторы `+, -, *, @, /` -- делают именно то, что обозначают

функции `sin, cos, exp` -- поэлементные

если нужны матричные функции -- `np.linalg`

## broadcasting

In [43]:
A = np.random.random((2, 2))
A

array([[0.02732452, 0.11037372],
       [0.44067171, 0.68121525]])

In [44]:
A + 1

array([[1.02732452, 1.11037372],
       [1.44067171, 1.68121525]])

In [45]:
A + [1, 2]

array([[1.02732452, 2.11037372],
       [1.44067171, 2.68121525]])

In [46]:
A + np.array([[1], [2]])

array([[1.02732452, 1.11037372],
       [2.44067171, 2.68121525]])

In [47]:
A = np.arange(4)
B = np.arange(5) * 10
print(A)
print(B)

A.reshape(-1, 1) + B

[0 1 2 3]
[ 0 10 20 30 40]


array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

Задания:
* написать функции активации, которые принимают и возвращают ndarray. sigmoid, tanh, ReLU, ReLU@k
* вспомнить Dense слой (fully-connected, linear)
* написать инициализатор для матрицы W: матрица размерности ($N_{in}$ x $N_{out}$), значения в которой -- случайные из промежутка  $$\pm \frac{\sqrt 6}{\sqrt N_{out}}$$

Задания на разные функции:
* соединить два заданных массива размерностей (4х2) и (7х2) вертикально, два массива размерностей (4x5) и (4x1) горизонтально (np.hstack, np.vstack)
* сгенерировать массив рандомных чисел и посчитать его статистики: среднее, дисперсию. повторить то же самое для n-мерного массива по разным осям, используя как методы, так и функции (np.mean, np.std)
* удалить заданную строку/столбец из массива, вставить строку/столбец на заданное место (np.delete, np.insert)
* cоздайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке
* проверьте, есть ли в двумерном массиве строка, полностью заполненная нулями. если есть, то замените значения в этой строке на среднее по столбцам
* Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i